export const userInitialState = {
  authenticated: false,
  avatar: null,
  batch: null,
  createdAt: null,
  dept: null,
  email: null,
  erpID: null,
  firstName: null,
  lastName: null,
  token: null,
  updatedAt: null,
  __v: null,
  _id: null,
};
